# Use postgres for development since heroku uses it as well
development:
  adapter: postgresql
  username: todobadour
  password: 
  encoding: unicode
  database: todobadour_development
  pool: 5

# Test uses sqlite for simplicity sake
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

# No production, heroku sets this up automatically
