development:
  adapter: mysql2
  username: dev
  password: gyiy3skr
  host: localhost
  database: todobadour_development

# Test uses sqlite for simplicity sake
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
  
# Production 
production:
  adapter: mysql2
  username: tdbd
  password: fkaqr90ß13u780r413qhjfnqiopFIN
  host: localhost
  database: todobadour
