# Use postgres for development since heroku uses it as well
development:
  adapter: postgresql
  username: todobadour
  password: 
  encoding: unicode
  database: todobadour_development
  pool: 5

# Test database used by rspec and cucumber
test: &test
  adapter: postgresql
  username: todobadour
  password: 
  encoding: unicode
  database: todobadour_testing
  pool: 5
#
# Cucumber database is the same as test
cucumber:
  <<: *test

# No production, heroku sets this up automatically

